# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25d3b8687279dcd6db1250badc960acffd98aa0994f554e6041eb2eaf5100593b0db68b323e8483fe5457f01ca93a5b5f294f83697c3c71d494a8c081257578c

test:
  secret_key_base: 4f5a8944ba90dde72628606831227225897665839fec81bfe9bbaeb09d183e3ee5315a38d3e511c709b0aa6bd7b2a7f6b2e10a394d0a132076092213d0975eb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
